#
# X-Ros base enviroment
#

FROM osrf/ros:humble-desktop-full
LABEL maintainer="Zhang Jianfei <zhangjianfei2005@126.com>"

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# create user with id 1000 (same with host user)
RUN useradd --shell /bin/bash -u 1000 -c "" -m user && usermod -a -G dialout user
RUN echo "user:1" | chpasswd && adduser user sudo

# setup virtual X server
RUN mkdir /tmp/.X11-unix && \
	chmod 1777 /tmp/.X11-unix && \
	chown -R root:root /tmp/.X11-unix
ENV DISPLAY :99

ENV TERM=xterm
ENV TZ=UTC-8

# create and start as LOCAL_USER_ID
COPY docker/scripts/xros_entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/bin/bash", "/usr/local/bin/entrypoint.sh"]

CMD [ "/bin/bash" ]
